---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package for Debian based distro.
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: install httpd and php package for CentOS
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

