---

- hosts: all
  become: true
  pre_tasks:


  - name: update repo cache (CentOS)
    tags: always
    yum: 
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Debian Distros.)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base


- hosts: work_stations
  become: true
  roles:
    - work_stations


- hosts: web_servers
  become: true
  roles:
    - web_servers
    

- hosts: db_servers
  become: true
  roles:
    - db_servers

