
  - name: install apache2 and php package on Debian based distros.
    tags: apache,php,ubuntu
    package:
      name: 
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
      state: latest

  - name: start httpd service on (CentOS)
    tags: start,apache,httpd,centos
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes

  - name: change webmaster email address
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin root@localhost.com
      backup: yes
    when: ansible_distribution == "CentOS"
    notify: restart_apache

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
