- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIgFm3xy5gBJGGPjVWoWxnH02RqaDPm+QLJQ1UQbPbmp Ubuntu-Admin"

- name: generate sshd_config file from template
  tags: ssh,sshd_config
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
